services:
  app:
    container_name: simple-api-pool
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "18080:18080"
    volumes:
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
